name: Build and upload binaries to release
on:
  push:
    tags:
      - '*'

jobs:
  backend:
    name: Release wasm binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
          override: true

      - name: Build
        run: cargo build --target wasm32-wasi --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/wasm32-wasi/release/main.wasm
          asset_name: main.wasm
          tag: ${{ github.ref }}
          overwrite: true
          body: "Override wasm module"

  frontend:
    name: Release UI assets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vanilla

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Build with Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - run: npm run build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vanilla/bin/**/*.{js,html}
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: "Override JS/HTML assets"

  manifest:
    name: Release manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload manifest to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: manifest.json
          asset_name: manifest.json
          tag: ${{ github.ref }}
          overwrite: true
          body: "Override manifest"